[package]
name = "tyto"
version = "0.1.0"
edition = "2018"
authors = ["Malhar Vora <malhar.vora@openanalytics.eu>"]


[dependencies]
actix-web="4.0.0-beta.10"
md5="0.7.0"
serde = "1.0.136"
toml="0.5.8"
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls" , "postgres", "json" ] }
snafu = "0.7.0"
