domain_name = "www.localhost.com"
ip = "127.0.0.1" # tyto will listen to this IP
port = 8400 # tyto will bind and accept requests on this port

db_host = "localhost"
db_port = 5432
db_name = "tyto"
db_user = "tyto"
db_password = ""

[email]
username = "testusername"
password = "testpassword"
server = "smtp.test.com"
sender = "sender@test.com"

