domain_name = "www.localhost.com"
activation_url = "www.localhost.com:8400/api/v1/users/activate"
ip = "127.0.0.1" # tyto will listen to this IP
port = 8400 # tyto will bind and accept requests on this port

db_host = "localhost"
db_port = 5432
db_name = "tyto"
db_user = "tyto"
db_password = ""

[email]
username = "testusername"
password = "testpassword"
server = "smtp.test.com"
sender = "sender@test.com"

# Authentication related configurations 
[auth]
key = "123456781234" # 12 character Base64 encoded key to be used to generate token
minutes = 1 # Minutes token remains valid for

